language: node_js
node_js:
  - '12'
dist: bionic
services:
  - docker
before_install:
  - docker build -t foursquare-demo -f ./Dockerfile.dev ./
cache: 
    - node_modules
script:
  - docker run -e CI=true foursquare-demo npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "foursquare-demo"
#   env: "foursquare-demo"
#   bucket_name: "elasticbeanstalk-us-west-2-811145310164"
#   bucket_path: "foursquare-demo"
#   edge: true
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY